import {
  DEFAULT_GENERIC_DURATION,
  DEFAULT_POMODORO_LONG_BREAK,
  DEFAULT_POMODORO_ROUNDS_BEFORE_LONG,
  DEFAULT_POMODORO_SHORT_BREAK,
  DEFAULT_POMODORO_WORK,
  DEFAULT_SIT_DURATION,
  DEFAULT_STAND_DURATION,
} from './constants'

export const DEFAULT_TIMER_SECONDS = {
  generic: DEFAULT_GENERIC_DURATION,
  sit: DEFAULT_SIT_DURATION,
  stand: DEFAULT_STAND_DURATION,
  work: DEFAULT_POMODORO_WORK,
  shortBreak: DEFAULT_POMODORO_SHORT_BREAK,
  longBreak: DEFAULT_POMODORO_LONG_BREAK,
} as const

export const DEFAULT_TIMER_MINUTES = {
  generic: Math.round(DEFAULT_TIMER_SECONDS.generic / 60),
  sit: Math.round(DEFAULT_TIMER_SECONDS.sit / 60),
  stand: Math.round(DEFAULT_TIMER_SECONDS.stand / 60),
  work: Math.round(DEFAULT_TIMER_SECONDS.work / 60),
  shortBreak: Math.round(DEFAULT_TIMER_SECONDS.shortBreak / 60),
  longBreak: Math.round(DEFAULT_TIMER_SECONDS.longBreak / 60),
} as const

export const DEFAULT_POMODORO_ROUNDS = DEFAULT_POMODORO_ROUNDS_BEFORE_LONG